function(enable_doxygen)
        set(DOXYGEN_CALLER_GRAPH YES)
        set(DOXYGEN_CALL_GRAPH YES)
        set(DOXYGEN_EXTRACT_ALL YES)
        set(DOXYGEN_GENERATE_HTML YES)
        set(DOXYGEN_GENERATE_MAN NO)
        set(DOXYGEN_GENERATE_XML NO)
        set(DOXYGEN_GENERATE_TREEVIEW YES)
        set(DOXYGEN_UML_LOOK YES)
        set(DOXYGEN_DOT_TRANSPARENT YES)
        set(DOXYGEN_DISABLE_INDEX NO)
        set(DOXYGEN_FULL_SIDEBAR NO)
        set(DOXYGEN_HAVE_DOT YES)
        set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/docs)

        find_package(Doxygen REQUIRED dot)
        if (DOXYGEN_FOUND)
            message(STATUS "Doxygen found")
        else()
            message("Doxygen not found")
        endif()

        doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR}/src)
endfunction()
