name: ShitStation Mac Build

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          set-safe-directory: true

      - name: Install dependencies
        run: brew install sdl2 dylibbundler

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target PSXEmulator -j4

      - name: Bundle App
        run: ./.github/bundle.sh

      - name: Sign
        run: codesign --force -s - -vvvv ShitStation.app

      - name: Zip it up and Zip it out
        run: zip -r ShitStation ShitStation.app

      - name: Upload App
        uses: actions/upload-artifact@v2
        with:
          name: ShitStation
          path: ShitStation.zip
