name: ShitStation Windows Build

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ShitStation -j4

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: Windows executable
          path: './build/RelWithDebInfo/ShitStation.exe'
